import React from 'react';
import Head from 'next/head';
import PageTitle from '@/components/PageTitle';
import ArticleOverview from '@/components/ArticleOverview';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {PageTitle('Welcome to my (not yet) static blog!')}
        {ArticleOverview([
          {
            slug: 'test',
            image:
              'https://images.unsplash.com/photo-1496128858413-b36217c2ce36?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=3603&q=80',
            // image: process.env.NEXT_PUBLIC_DIRECTUS_URL + 'assets/' + imageUuid,
            pretitle: 'Statisch',
            title: 'Test',
            description: 'Test',
          },
          {
            slug: 'test-2',
            image:
              'https://images.unsplash.com/photo-1547586696-ea22b4d4235d?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=3270&q=80',
            // image: process.env.NEXT_PUBLIC_DIRECTUS_URL + 'assets/' + imageUuid,
            pretitle: 'Gegenereerde',
            title: 'Test',
            description: 'Test',
          },
          {
            slug: 'test-3',
            image:
              'https://images.unsplash.com/photo-1492724441997-5dc865305da7?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=3270&q=80',
            // image: process.env.NEXT_PUBLIC_DIRECTUS_URL + 'assets/' + imageUuid,
            pretitle: 'Website',
            title: 'Test',
            description: 'Test',
          },
        ])}
      </main>
    </>
  );
}
